spring.profiles.active=dev
# ContextPaths are for High-level URL's
server.error.whitelabel.enabled=false
mybatis.mapper-locations=mybatis/mappers/**/*.xml
app.pepper.value=${SALT_VALUE}
app.bcrypt.iterations=${BCRYPT_ITERATIONS}
spring.jackson.default-property-inclusion = NON_NULL

app.oauth.issuer=${OAUTH_ISSUER}
app.oauth.token-ttl-seconds=300
app.oauth.allow-insecure-localhost=false
